### ISSUE TITLE
Adjust naming convention for GH workflow Create Release

### ISSUE THREAD

**Issue by triffer** [kyma-project/istio#1066]
**Description**

As described in documented [test strategy](TBD) adjust naming for GH Workflow Create Release. 

**ToDos [Developer]**

- [x] Find all workflow/jobs related to release
- [x] Rename workflow filenames, also names and calling them without other workflows
- [x] Adapt documentation / update links  

**PRs**

- [x] https://github.com/kyma-project/istio/pull/1179

**ACs [PO]**

- [x] Workflow names and file names adapted for release related workflows
- [x] changes updated in ci-cd.md

**DoD [Developer & Reviewer]**

- [x] Provide documentation.

**Attachments**

- part of: #1162

**Comment by strekm** [comment]
Accepted proposal:

`pull` for PR workflows that runs on main and release branches
`post` for workflows running on the main branch
`schedule` for scheduled workflows running on main branch
`release` for workflows running on the release of a module

for workflow_call files introduce naming convention to prefix it with `call`.
