### ISSUE TITLE
Istio integration tests - separate test suites and parallelize them into new jobs

### ISSUE THREAD

**Issue by kolodziejczak** [kyma-project/istio#1067]
**Description**

As a part of the team goal we are aiming to reduce time of the CI test jobs execution. To achieve that we decided to split sequential integration tests execution to many parts in parallel. To achieve that we should split the main test suite into more fine grained tests suites, that will be running in a separate jobs in parallel.

**Motivation**

Reduction of the execution time of the integration tests in the Istio Module repository.

Contact(s): PO; ...

**ToDo [Developer]**
- [x] find best way to split main test suite to the fine grained ones
- [x] write a little of code for that
- [x] create Makefile targets for those test suites
- [x] Add jobs for k3d integration tests
- [x] Add jobs for Gardener integration tests
- [x] update CICD docs

**PRs**
- https://github.com/kyma-project/istio/pull/1080
- https://github.com/kyma-project/istio/pull/1084

**AC [PO]**
- [x] Main test suite split into more fine grained test suites
- [x] Freshly introduced test suites run in separate parallel jobs
- [x] Tests execution time reduced significantly
- [x] CICD docs updated

**Attachments**
- [APIGateway module PR](https://github.com/kyma-project/api-gateway/pull/1232)
- [Istio feature files](https://github.com/kyma-project/istio/tree/main/tests/integration/features/istio/production/main-suite)
- [Dynamic job matrices in GHA](https://developer-friendly.blog/blog/2024/03/09/github-actions-dynamic-matrix)

**Comment by kolodziejczak** [comment]
We achieved improvement in the integration tests time of execution
Gardener: ~50min -> ~20min
k3d: ~20min -> ~10min
