### ISSUE TITLE
Improve test runs to avoid redundancy

### ISSUE THREAD

**Issue by triffer** [kyma-project/istio#1068]
**Description**

Get to an agreement in the team where we want to run what tests, e.g. all tests in PRs only run on k3d, all tests on main and release branches run on Gardener.  
The focus should be to avoid executing the same tests more than once on the same code.
We should consider the runtime of the tests and fast feedback as a criteria.

**Motivation**

Fulfill AC `Reduce job runs count, ensure all jobs have clear responsibility and meaning` from our team goal.

**ToDo [Developer]**
- [x] Prepare proposal on what to run where
  - [x] Discuss if compatibility tests have the right purpose or if this can be done as part of the integration test job with an additional step.
  - [x] Find potential duplicated test executions across PR targets, e.g. PR merge to main, running on main, PR merge to release and running on main) 
  - [x] Consider if all Gardener tests must run on PRs
  - [x] Consider running UI tests only on main
  - [x] Consider outcome of [Slack poll](https://sap-btp.slack.com/archives/C01L56SQ0QH/p1729075495652509) where to run tests
- [x] Schedule a meeting to present proposal to the team
- [x] Create a followup meeting and discuss remaining issues

**PRs**
- 

**AC [PO]**
- [x] Outcome/test strategy is documented
- [x] Created follow up issue to adapt workflows in Istio and API Gateway

**DoD [Developer & Reviewer]**
- [x] Provide documentation.
