### ISSUE TITLE
Clean up old Workflow runs

### ISSUE THREAD

**Issue by triffer** [kyma-project/istio#1069]
**Description**

Clean up workflows that no longer exist, but are still visible in the [Actions UI](https://github.com/kyma-project/istio/actions). Those workflows can be easily detected by checking if they have a link to existing yaml file.
To avoid additional work this issue might be only done after the issue [Introduce naming scheme for workflow names and workflow files](https://github.com/kyma-project/istio/issues/1066) is completed, because in the mentioned issue the structure of workflows might change.

**Motivation**

Better visibility and up to date Actions on the UI.

**ToDo [Developer]**
- [x] Remove workflow runs that no longer exists in the pipelines

**PRs**
- [ ] https://github.com/kyma-project/istio/pull/1119

**AC [PO]**
- [x] Workflows that no longer exists are no longer visible in the [Actions UI](https://github.com/kyma-project/istio/actions)
- [x] Follow up for API Gateway is created or Workflows are also clean up for API Gateway

**Comment by Ressetkk** [comment]
For future reference. The script lists 500 recent workflow runs and concurrently will issue a deletion 15 at a time.
```
gh run list --json databaseId -q '.[].databaseId' -w {WORKFLOW_FILE} --limit "500" |
            xargs -IID -P 15 gh run delete ID
```
