### ISSUE TITLE
Extend Istio CR with Egress 

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#1159]
**Description**

Based on [ADR](https://github.com/kyma-project/istio/blob/main/docs/contributor/adr/0009-egress-gateway.md) extend Istio CR to support lifecycle Istio Egress component. There should be possibility to enable / disable component. There should be possibility to configure kubernetes properties of Istio Egress. Configuration should be validated to avoid misconfigurations. 
Adding e2e tests is not in scope of this issue.

**Reasons**

Provide managed and configurable Istio Egress

**Contact**

**ToDos [Developer]**

- [x] Extend Istio API with Egress gateway
- [x] Extend Istio operator YAMLs templating to support Egress
- [x] Extend existing integration test to verify resource configuration for egress is applied
- [x] Extend existing operator documentation if necessary
- [x] Add restart of egress gateway (consider ingress gateway restart criteria)

**PRs**

- https://github.com/kyma-project/istio/pull/1178
- https://github.com/kyma-project/istio/pull/1196
- https://github.com/kyma-project/istio/pull/1197
- https://github.com/kyma-project/istio/pull/1198

**ACs [PO]**

- [x] Egress should be disabled by default
- [x] Egress can be enabled / disabled
- [x] Egress can be configured
- [x] Egress configuration is validated
- [x] Egress reconciliation is included in Istio CR status

**DoD [Developer & Reviewer]**

- [x] Provide unit and integration tests.
- [x] Provide documentation.
- [x] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
- [x] If you changed the resource limits, explain why it was needed.
- [x] If the default configuration of Istio Operator has been changed, you performed a manual upgrade test to verify that the change can be rolled out correctly.
- [x] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.
- [x] Add release notes.

**Attachments**

- [ADR](https://github.com/kyma-project/istio/blob/main/docs/contributor/adr/0009-egress-gateway.md)
- part of: #419 

**Follow-Up Issues**

- [...]()
