### ISSUE TITLE
Simplified GH Workflows

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#1162]
**Description**

Goal is to introduce simplified, lightweight GH workflows as a balance between quality and development experience. GH workflows should be consistent between our projects. Idea is to introduce minimal testing on PR issued to main and to release branches that run only on k3d cluster. PR workflow should be fast and reliable. Main workflow beside tests running on k3d should introduce tests executed on gardener (AWS, GCP). Same approach should be applied on release workflow. Schedule workflow should run all available tests ran on k3d and Gardener AWS.

**ToDos [Developer]**
- [x] [align on document strategy](https://github.com/kyma-project/istio/issues/1068)
- [x] [document test strategy](https://github.com/kyma-project/istio/issues/1165)
- [x] create / adjust pull workflow that builds own image, execute lint and unit tests, execute integration tests on k3d
- [x] [create / adjust post workflow](https://github.com/kyma-project/istio/issues/1244)
- [x] [create / adjust release workflow](https://github.com/kyma-project/istio/issues/1163)
- [x] [Adjust naming convention for GH Workflows Create Release](https://github.com/kyma-project/istio/issues/1066)
- [x] update DoD to include: "Successful tests run on main after merge of the PR" -> @kasiakepka 
- [x] update API Gateway release process to link green run of create release workflow (project card) -> @kasiakepka
