### ISSUE TITLE
Create Release GH Workflow

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#1163]
**Description**

Create / adjust release workflow that builds production image with image-builder, execute lint and unit tests, integration tests, AWS specific integration tests, GCP specific integration tests, and upgrade tests.

**ToDos [Developer]**

- [x]  remove post merge runs to release branch
- [x]  do not run tests on sec config changes and eventually version changes
- [x]  extend create release workflow to execute tests on release artefact
- [x]  failing tests should block GH Release creation
- [x]  there should be possibility to run tests if failed previously
- [x]  extend Release module template with TODO to link green create release workflow
- [x]  Add notification at the end of the create release workflow, so we get a cool notification on Slack after releasing

**PRs**

- [x] https://github.com/kyma-project/istio/pull/1161

**Attachments**

- part of: https://github.com/kyma-project/istio/issues/1162
