### ISSUE TITLE
User EnvoyFilter targeting Istio Ingress Gateway should result in Istio CR in Warning state

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#1168]
**Description**

Extend Istio CR reconciliation to check if user created Istio EnvoyFilter configuring Istio Ingress Gateway is present on a cluster. Such Istio EnvoyFilter can significantly alter or even break Istio Ingress Gateway. User should be notified that he applied potentially dangerous configuration. When such Istio EnvoyFilter is detected during a reconciliation Istio CR status should be set to Warning state. Additionally new specific condition should be introduced to simplify troubleshooting. Description message should clearly state EF name, namespace and fact targeting Istio Ingress Gateway.

Misconfigured EF is rejected by Istio Ingress Gateway although error occurs when Istio Ingress Gateway is restarted. Reasons for restarting Istio Ingress Gateway are related to configuration changes as well as Istio upgrades. When this happens Istio CR should be in error state.

**Reasons**

Making user more aware of potential harmful global configuration.

**ToDos [Developer]**

- [x] Get familiar with code
- [x] Add tests for all relevant cases
- [x] Implement status / condition for when EF is applied on IGW
- [x] Think about integration tests
- [x] Docs, RN
- [x] Inform SRE / think about troubleshooting guide

**PRs**

- [x] https://github.com/kyma-project/istio/pull/1442

**ACs [PO]**

- [x] Istio CR in Warning state if user create EF targeting Ingress Gateway is present on a cluster
- [x] Istio CR in Error state if Ingress Gateway / Istiod can't be started
- [x] troubleshooting guide created

**DoD [Developer & Reviewer]**

- [x] Provide unit and integration tests.
- [x] Provide documentation.
- [x] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
- [x] If you changed the resource limits, explain why it was needed.
- [x] If the default configuration of Istio Operator has been changed, you performed a manual upgrade test to verify that the change can be rolled out correctly.
- [x] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.
- [x] Add release notes.

**Comment by kolodziejczak** [comment]
IstioCR will go into the `Error` state in case if EnvoyFilter breaks `istio-ingressgateway`. It will be done because of the implementation of the Istio installation library we use. Let's explain why. There are 2 reasons for the module to restart:
1. Istio mesh version is bumped in the new version of the Istio module
2. In a given version of Istio Module there are compatibility env variables that apply to data plane (it's not in every version)

- In the 1st case all works well, because in addition Error state, there will be a message indicating that the installation failed, which is true in this case
- In the 2nd - Reconciliation is built with a certain order in which steps must be performed.  If the user turns on the compatibility mode in the module, there is a data plane restart triggered. In case if there are any EnvoyFilters breaking istio-ingressgateway in the cluster, the new Pods won't get up. It will be detected by the Istio installation library, which will put IstioCR in the Error state. Another place where we could implement such detection is restart logic, but we cannot run it before installation is done. Unfortunately it will be a bit misleading. It will state that the installation failed in the IstioCR status. There is no simple way to fix that, since we don't control Istio installation library implementation.
