### ISSUE TITLE
introduce internal structure replacing Istio Operator file

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#1172]
**Description**

Istio dropped struct for IstioOperator that is used to manage Istio configuration in Istio module. Based on default configuration and user configuration merged configuration is prepared and passed to Istio installation. IstioOperator was strongly typed and validated. Goal of this task is to introduce internal Istio module type that is representing configuration based on default and Istio CR configuration options. This structure needs to be subset of IOP and accepted by installation method from istio. Introduced type should support only what comes from default configuration and Istio CR configurations.

**Reasons**

**ToDos [Developer]**

- [x] adapt the merge functions from IstioCR to the IstioOperator replacement
- [x] bump Istio library in the Istio module to 1.24

**PRs**

- https://github.com/kyma-project/istio/pull/1192

**ACs [PO]**

- [x] internal type holding Istio configuration introduced

**DoD [Developer & Reviewer]**

- [x] Provide unit and integration tests.
- [x] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
- [x] If you changed the resource limits, explain why it was needed.
- [x] If the default configuration of Istio Operator has been changed, you performed a manual upgrade test to verify that the change can be rolled out correctly.
- [x] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.

**Attachments**

- https://github.com/istio/istio/pull/52541/files#diff-d86a8e50d8e8bd68f9ea59bf4c168587cb42a7932153cc3f2e6fc1ec0be5ac16
