### ISSUE TITLE
Egress e2e test

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#1201]
**Description**

Based on https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/ and internal script create automated e2e test. Assuming gardener AWS(?) cluster, having Istio installed. The test should execute following scenario:
- enable egress
- create test istio injected namespace
- deploy curl
- deploy NetworkPolicy to limit egress traffic from test namespace to kube-system and to istio-system
- test that external service a is not reachable
- test that external service b is not reachable
- create corresponding Istio resources to allow routing to external service a only through egress (Gateway, DestinationRule, VirtualService)
- test that external service a is reachable
- test that external service b is not reachable
- clean up

open questions:
- should we test egress traffic from other ns to make sure we are not blocking traffic

**ToDos [Developer]**

- [x] ...

**PRs**

- [x] https://github.com/kyma-project/istio/pull/1289

**ACs [PO]**

- [x] e2e test created, testing outgoing traffic limited to specific service
- [x] e2e test triggered on post and release WH
- [x] ci/cd docu updated if needed

**DoD [Developer & Reviewer]**

- [x] Provide unit and integration tests.
- [x] Provide documentation.
- [ ] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
- [x] If you changed the resource limits, explain why it was needed.
- [x] If the default configuration of Istio Operator has been changed, you performed a manual upgrade test to verify that the change can be rolled out correctly.
- [x] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.
- [x] Add release notes.

**Attachments**

part of: https://github.com/kyma-project/istio/issues/419
https://github.com/kyma-project/istio/blob/main/docs/user/tutorials/01-50-send-requests-using-egress.md

**Comment by barchw** [comment]
Test should add another request header from the egress to make sure it works.
