### ISSUE TITLE
Prepare customer-facing documentation for the Istio module

### ISSUE THREAD

**Issue by nataliasitko** [kyma-project/istio#146]
**Description**
For the new modularization approach, we need documentation that is common for all the modules, e.g. general description (landing page), getting started, module configuration, etc. 

**AC**
- [x] Your audience is the end-user so the documentation must be written for them (not for the team that builds this module, or other SAP teams that wish to build a module, not for SRE, etc). Remember about the context. How much user knows by now (probably just high level knowledge about Kyma as a whole and that there are modules).
- [x] The documentation must be consumable by the kyma-project.io home page (split into several information types/md files)
- [x] Create a docs folder following the standard structure proposed in -> [this DR](https://github.com/kyma-project/kyma/issues/16775)
- [ ] In each module's documentation include:
  - [x]  General description of the functionality (~if the module is mandatory, mention it!~)
  - [x]  Getting Started - instructions on how to use the module. The module docs must mention the prerequisite that the module must be enabled (don't explain 'how', just link to the generic document we (will) have on how to enable modules in Kyma (see [Adjust the Get Started docs to modular approach](https://github.com/kyma-project/kyma/issues/16778))
  - [x] Module configuration
  - [x] Instructional documents (currently called "dev tutorials" and "operational guides") - must be isolated, i.e. no dependencies on other tutorials or modules. An example of a happy path for the user. - _adding the tutorials will be part of [this issue]_(https://github.com/kyma-project/istio/issues/294)
  - [x] If needed, troubleshooting
  - [x] Instructions on how to give feedback
  - [x] CRD documentation (if needed) - _ full and up-to-date CRD ducumentation was added. For now it is not autogenerated as we automatically fetch the fields' descriptions from the Kubernetes afinifty package (they are not in-line with the content guidelines and cannot be edited) and the table generated by the tool is too long to be included in the doumentation (a lot of unnecessary details and repetitions)._ 

**Reasons**

Prepare documentation for modular Kyma. 

**Assignees**

@kyma-project/technical-writers

**Attachments**
https://github.com/kyma-project/kyma/issues/16421

**Comment by triffer** [comment]
Input for Proxy restart documentation:

**Restart of workloads with enabled sidecar injection**

When the Istio version is upgraded or the resource configuration of the proxies changes, a restart of the pods with Istio injection enabled is performed.
For all resources where a rolling restart can be performed, this is done automatically. 
If the resource is a job, a ReplicaSet that is not managed by a deployment, or a pod that is not managed by any other resource, the restart cannot be performed automatically. For these workloads, a warning is logged and they must be restarted manually.

**Comment by nataliasitko** [comment]
Initial PR: https://github.com/kyma-project/istio/pull/170
