### ISSUE TITLE
Limit amount of proxy restarts during one reconciliation

### ISSUE THREAD

**Issue by triffer** [kyma-project/istio#155]
**Description**

During reconciliation we read all proxies to filter out proxies that needs to be restarted. Since the amount of proxies is not deterministic we should introduce two safe-guards. 
1. We should limit how many proxies we read by using pagination.
2. We should limit how many proxies we restart during one reconciliation.

By implementing this feature we'll make sure that the reconciliation is more responsible, since we are not blocking the reconciliation loop for a long time if there are many proxies to be restarted. 
We should define some starting values, e.g. limit proxy restart to 30 and measure how this performs.

**Reasons**

Increase stability and reliability of the reconciliation of the Istio module.

**TODO**:
- [x] Get familiar with code
- [x] Basic implementation
- [x] ~~Introduce `envtest` since controller fake client do not support pagination~~ did not workout due to list condition for pods to be in `Running` `status.phase`
- [x] Refine tests and implementation
- [x] ~~Integration test needed?~~ too difficult to implement with reasonable efforts and reliability
- [x] Manual testing
- [x] Discuss few points on solution - https://sap-btp.slack.com/archives/C01L56SQ0QH/p1721045723840319
- [x] Utilize continue token between reconciliations + proper Ready condition for reconciliation runs
* run as POC and worked but unreliable (missed pods) - decided to keep it simple and avoid sharing context between reconciliations to avoid complexity also when continue token becomes invalid and unsure how to handle this case. we should rather tune limit parameters instead for now.
- [x] Review 

**Findings**:
- Client Cache must be excluded for `Pod` resources. With Cache turned one the Client did not return a Continue token when Limit was specified.

**DoD:**
- [x] provide documentation
- [x] release notes and What's New updates for Kyma customers
- [x] provide unit tests
- [x] ~~provide integration tests~~ n/a
- [x] test on production-like environment
- [x] verify resource limits
- [x] ~~followup issue~~ n/a

**Attachments**

https://kubernetes.io/docs/reference/using-api/api-concepts/#retrieving-large-results-sets-in-chunks

**PR**
- [x] https://github.com/kyma-project/istio/pull/926
