### ISSUE TITLE
[MVP] Istio component

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#38]
**Description**

First version of Istio component matching functionality of Istio reconciler. First phase of migration. First implementation does not remove dependency to `global.domainName`. 

TODO:
- [x] implementation (reconciliation, upgrades)
- [x] pipelines (testing, releasing, component testing)
- [x] tests implementation
- [x] documentation
- [x] migration
- [x] rollout

TASKS:
- [x] [support for installation](https://github.com/kyma-project/istio/issues/4)
- [x] [support for upgrade](https://github.com/kyma-project/istio/issues/55)
- [x] [support for uninstallation](https://github.com/kyma-project/istio/issues/81)
- [x] [support for proxy reset](https://github.com/kyma-project/istio/issues/66)
- [x] [pipeline building and unit testing component](https://github.com/kyma-project/test-infra/issues/6637)
- [x] [pipeline building Istio module](https://github.com/kyma-project/istio/issues/82)
- [x] [version checking](https://github.com/kyma-project/istio/issues/124)
- [x] [blocking deletion strategy](https://github.com/kyma-project/istio/issues/128)
- [x] [support for resources and HPA](https://github.com/kyma-project/istio/issues/143)
- [x] [component tests](https://github.com/kyma-project/istio/issues/137)
- [x] [PR related pipeline](https://github.com/kyma-project/test-infra/issues/7564)
- [x] [release related pipelines](https://github.com/kyma-project/test-infra/issues/7761)
- [x] [time based reconcile](https://github.com/kyma-project/istio/issues/181)
- [x] [domainName support](https://github.com/kyma-project/istio/issues/183)
- [x] [security scans conf](https://github.com/kyma-project/istio/issues/186)
- [x] [UI for Istio CR](https://github.com/kyma-project/istio/issues/284)
- [x] [migration POC](https://github.com/kyma-project/istio/issues/148)
- [x] dev env migration 
- [x] [documentation](https://github.com/kyma-project/istio/issues/146)
- [x] 1.0 release
- [x] stage env migration
- [x] synchronise istio component values with istio module
- [x] prod env migration

**Reasons**

part of modularisation

**DoD:**
- [x] provide documentation
- [x] provide unit tests
- [x] test on SKR
- [x] verify resource limits
- [x] followup issue
- [x] publish release notes and _What's New_ updates for Kyma customers

**Attachments**
[technical design](https://github.com/kyma-project/istio/issues/32), migration proposal

**Comment by strekm** [comment]
https://github.com/kyma-project/istio/issues/157 is a blocker for Istio GA
https://github.com/kyma-incubator/reconciler/issues/1362 is a blocker for staging migration
