### ISSUE TITLE
Support for egress gateway component

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#419]
**Description**

Atm Kyma Istio comes with Istiod and Ingress gateway enabled by default. Add possibility to enable and configure Istio egress gateway component in similar way as other components. There should be possibility to configure kubernetes resources, HPA. 

TODOs:
- [x] [ADR](https://github.com/kyma-project/istio/issues/1070)
- [x] threat modelling
- [x] [implementation](https://github.com/kyma-project/istio/issues/1159)
- [x] [automated e2e tests](https://github.com/kyma-project/istio/issues/1201)
- [x] [basic tutorial ](https://github.com/kyma-project/istio/issues/1247)
- [x] [mtls origination tutorial](https://github.com/kyma-project/istio/issues/1269)

**Reasons**

Adding possibility to enable egress gateway

**Attachments**

https://github.com/kyma-project/istio/blob/main/docs/user/03-technical-reference/istio-custom-resource/01-30-istio-custom-resource.md

**Comment by abbi-gaurav** [comment]
One requirement from a team:
- We need working example on how to configure Istio egress mTLS
- When java application makes external call to some URL istio should make HTTPS connection and if server has appropriate CA attach our client certificate

@strekm, please comment if this would be feasible or not.
if not, what are the alternates

**Comment by i064689** [comment]
@strekm  could you please help us with a working example on how to configure Istio egress mTLS

**Comment by strekm** [comment]
> We need to understand if the egress gateway is also just another envoy proxy where access logs can be enabled the same way as with ingress gateway, and enrich the documentation accordingly.

@a-thaler egress is just another proxy. i did not find any ingress / egress specific configuration where it comes to access logs so it is safe to assume this is common.
