### ISSUE TITLE
[WIP] Support for FXCC

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#428]
**Description**
TBD

ACs:
- [ ] POC
- [ ] TBD

Decision:
- [ ] should this conf be exposed to end user

**Reasons**

**DoD:**
- [ ] Create a follow-up issue.
- [ ] Provide unit tests.
- [ ] Provide integration tests.
- [ ] Provide documentation.
- [ ] Test on a production-like environment.
- [ ] Check the outcome of all related pipelines.
- [ ] Verify resource limits.
- [ ] As a PR reviewer, verify code coverage and evaluate if it is acceptable.
- [ ] Create a release and bump in Kyma.
- [ ] Add release notes and What's New notes for Kyma customers.

**Attachments**

https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/#configuring-x-forwarded-client-cert-headers

**Comment by strekm** [comment]
As stated in [Istio docu](https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/#configuring-x-forwarded-client-cert-headers) no additional configuration is needed for XFCC. Default value for `forwardClientCertDetails` is `SANITIZE_SET`, which should be sufficient to cover most cases. 

There's [API Gateway module docu](https://kyma-project.io/#/api-gateway/user/tutorials/01-50-expose-and-secure-a-workload/01-54-expose-and-secure-workload-with-certificate) on how to secure a workload with certificate.

Finally there's [feature request filed in API Gateway module](https://github.com/kyma-project/api-gateway/issues/808) to make that flow part of APIRule.
