### ISSUE TITLE
Remove version v1alpha1 of Istio Custom Resource, Step 1

### ISSUE THREAD

**Issue by barchw** [kyma-project/istio#642]
**Description**

Remove Istio `v1alpha1` in favour of `v1alpha2`

**Reasons**

Istio `v1alpha1` was deprecated with rollout of Istio module.

**TODO**
- [x] Analyse all clusters if they all have v1alpha2 as stored version
```
❯ kcp taskrun --gardener-kubeconfig=./kcp/kubeconfig-garden-kyma-dev.yaml -t all -p 16 -- kubectl get crds istios.operator.kyma-project.io -o=jsonpath='{.status.storedVersions}' >> storedVersions.txt
❯ kcp taskrun --gardener-kubeconfig=./kcp/kubeconfig-garden-kyma-stage.yaml -t all -p 16 -- kubectl get crds istios.operator.kyma-project.io -o=jsonpath='{.status.storedVersions}' >> storedVersions.txt
❯ kcp taskrun --gardener-kubeconfig=./kcp/kubeconfig-garden-kyma.yaml -t all -p 16 -- kubectl get crds istios.operator.kyma-project.io -o=jsonpath='{.status.storedVersions}' >> storedVersions.txt
❯ grep -e "\[\"v1alpha1\"\]" storedVersions.txt
```
did not show any results for clusters with only v1alpha1 storage version
- [x] Remove v1alpha1 as stored version for all clusters - [need SRE support](https://sap-btp.slack.com/archives/CQF0V9075/p1723469940345339), following [official migration guide](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#upgrade-existing-objects-to-a-new-stored-version)
```
kcp taskrun --gardener-kubeconfig=./kcp/kubeconfig-garden-kyma-dev.yaml -t all -p 16 -- kubectl patch customresourcedefinitions istios.operator.kyma-project.io --subresource='status' --type='merge' -p '{"status":{"storedVersions":["v1alpha2"]}}'
kcp taskrun --gardener-kubeconfig=./kcp/kubeconfig-garden-kyma-stage.yaml -t all -p 16 -- kubectl patch customresourcedefinitions istios.operator.kyma-project.io --subresource='status' --type='merge' -p '{"status":{"storedVersions":["v1alpha2"]}}'
kcp taskrun --gardener-kubeconfig=./kcp/kubeconfig-garden-kyma.yaml -t all -p 16 -- kubectl patch customresourcedefinitions istios.operator.kyma-project.io --subresource='status' --type='merge' -p '{"status":{"storedVersions":["v1alpha2"]}}'
```
change requests in Notes section

```
❯ kcp taskrun --gardener-kubeconfig=./kcp/kubeconfig-garden-kyma-dev.yaml -t all -p 16 -- kubectl get crds istios.operator.kyma-project.io -o=jsonpath='{.status.storedVersions}' | grep v1alpha1
❯ kcp taskrun --gardener-kubeconfig=./kcp/kubeconfig-garden-kyma-stage.yaml -t all -p 16 -- kubectl get crds istios.operator.kyma-project.io -o=jsonpath='{.status.storedVersions}' | grep v1alpha1
❯ kcp taskrun --gardener-kubeconfig=./kcp/kubeconfig-garden-kyma.yaml -t all -p 16 -- kubectl get crds istios.operator.kyma-project.io -o=jsonpath='{.status.storedVersions}' | grep v1alpha1
```

showed empty results, all CRDs were updated, so only stored `istios` are in v1alpha2 version.

- [x] Merge https://github.com/kyma-project/istio/pull/976 and we wait for release Istio + rollout to regular channel.

**AC**
- [x] Make sure that v1alpha1 is not a served version
- [x] Make sure that all v1alpha1 Istios were migrated in storage to v1alpha2 (since we are annotating Istio CR during reconciliation, it should be already done)

**PR**
- [x] https://github.com/kyma-project/istio/pull/976 (main)
- [x] https://github.com/kyma-project/istio/pull/980 (release-1.8)
- [x] update RMA operator configuration to list/watch only v1alpha2 version (link in notes)

**Follow-up task**
https://github.com/kyma-project/istio/issues/979
