### ISSUE TITLE
Extend XFF support for other LBs

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#745]
**Description**

As of now Istio CR allows only to configure `numTrustedProxies`. This setting is not fully supporting all LB types. Properly configuring `numTrustedProxies` on AWS (TCP Proxy LB) will properly populate caller IP in XFF. This approach is not sufficient for Network LB. Also Istio installed on OpenStack cluster needs to be configured in slightly different way.

TODO:
- [x] [XFF on Network LB](https://github.com/kyma-project/istio/issues/718)
- [x] XFF on OpenStack cluster 
- [ ] rollout

**Reasons**

More coverage for XFF feature

**DoD:**
~~- [ ] Provide unit and integration tests.~~
- [ ] Provide documentation.
- [ ] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
~~- [ ] If you changed the resource limits, explain why it was needed.~~
- [ ] If the default configuration of Istio Operator has been changed, you performed a manual upgrade test to verify that the change can be rolled out correctly.
~~- [ ] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.~~
~~- [ ] Add release notes.~~

**Attachments**
https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/#configuring-x-forwarded-client-cert-headers
https://istio.io/latest/docs/tasks/security/authorization/authz-ingress/
