### ISSUE TITLE
[Automation] Create PR to update sec-scanners-config.yaml

### ISSUE THREAD

**Issue by barchw** [kyma-project/istio#925]
**Description**
Create a scheduled, weekly job, that will update the image version in `sec-scanners-config.yaml`

**Reasons**
- Automation of manual task

Pre-reqs:
- [x] https://github.com/kyma-project/api-gateway/issues/1234

**ToDos [Developer]**
- [x] Check with kyma-security if we actually can create an automated PR (we can use some goat bot like @kyma-gopher-bot)
- [x] Use Github service account creator tool to create this account
