### ISSUE TITLE
[after 06.09] Remove version v1alpha1 of Istio Custom Resource, Step 2

### ISSUE THREAD

**Issue by videlov** [kyma-project/istio#979]
**Description**

Remove Istio `v1alpha1` in favour of `v1alpha2`. This is the follow-up task of https://github.com/kyma-project/istio/issues/642

**Reasons**

Istio `v1alpha1` was deprecated with rollout of Istio module.

**Prerequisites**

Istio released and rolled out to regular with: https://github.com/kyma-project/istio/pull/976

**Todo**
- [x] Remove the old version `v1alpha1` from the source code and as a result in CRD too
- [x] update tutorials to newer version

**AC**
- [x] Remove v1alpha1 from CRD
- [x] Remove API code from Istio

**PR**
- https://github.com/kyma-project/istio/pull/1062

**Good to know**
https://github.tools.sap/kyma/backlog/issues/6059#issuecomment-7498452

**Comment by strekm** [comment]
@videlov please create internal task for SRE

**Comment by ebensom** [comment]
Please prioritize this, affecting: https://github.tools.sap/kyma/backlog/issues/6059
